sources:
  - name: s1
    database: dev_db
    schema: bronze
    tables:
      - name: orders
      - name: customers
      - name: payment
      - name: t_cust_info
  - name: s2
    database: dev_db
    schema: dev_Schema
    tables:
      - name: t_tickets